name: Validate pull title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    name: Validate pull title
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          allowed_prefixes: 'TRI-'
          github_token: ${{ github.token }}
